In [4]:
2+3


[1] 5

In [3]:
6/3


[1] 2

In [2]:
(3+8)/(2*3)


[1] 1.833333

In [1]:
log(12)

[1] 2.484907

In [5]:
sqrt(121)

[1] 11

In [12]:
x <- 1:10
cat(x)
cat('mean of x is:',mean(x))
cat('median of x is:',median(x))
cat('Varience of x is:',var(x))
cat('Standard deviation of x is:',sd(x))

1 2 3 4 5 6 7 8 9 10mean of x is: 5.5median of x is: 5.5Varience of x is: 9.166667Standard deviation of x is: 3.02765

In [13]:
cat(x,'\n')
cat('mean of x is:',mean(x),'\n')
cat('median of x is:',median(x),'\n')
cat('Varience of x is:',var(x),'\n')
cat('Standard deviation of x is:',sd(x),'\n')

1 2 3 4 5 6 7 8 9 10 
mean of x is: 5.5 
median of x is: 5.5 
Varience of x is: 9.166667 
Standard deviation of x is: 3.02765 


In [14]:
print(x)
print(paste('mean of x is:',mean(x)))
print(paste('median of x is:',median(x)))
print(paste('Varience of x is:',var(x)))
print(paste('Standard deviation of x is:',sd(x)))

 [1]  1  2  3  4  5  6  7  8  9 10
[1] "mean of x is: 5.5"
[1] "median of x is: 5.5"
[1] "Varience of x is: 9.16666666666667"
[1] "Standard deviation of x is: 3.02765035409749"


In [15]:
x <- 8+7
x

[1] 15

In [16]:
x <- "dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] "dataset"

[1] "character"

[1] "character"

[1] 1

NULL

In [17]:
x <- 23
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "numeric"

[1] "double"

[1] 1

NULL

In [18]:
x <- 23L
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "integer"

[1] "integer"

[1] 1

NULL

In [19]:
x <- 2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 2+3i

[1] "complex"

[1] "complex"

[1] 1

NULL

In [20]:
x <- TRUE
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] TRUE

[1] "logical"

[1] "logical"

[1] 1

NULL

In [22]:
vector()

logical(0)

In [23]:
vector("character",length=5)

[1] "" "" "" "" ""

In [24]:
character(5)

[1] "" "" "" "" ""

In [25]:
numeric(5)

[1] 0 0 0 0 0

In [26]:
logical(5)

[1] FALSE FALSE FALSE FALSE FALSE

In [27]:
x <- c(12,23,34,45,56)

In [28]:
x
class(x)


[1] 12 23 34 45 56

[1] "numeric"

In [30]:
x <- c(12L,23L,34L,45L,56L)
x
class(x)
length(x)

[1] 12 23 34 45 56

[1] "integer"

[1] 5

In [31]:
y <- c(TRUE,TRUE,FALSE,FALSE,TRUE)
y
class(y)
length(y)

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] "logical"

[1] 5

In [32]:
z<-c("sarah","tracy","Vamsi")
z
class(z)
length(z)

[1] "sarah" "tracy" "Vamsi"

[1] "character"

[1] 3

In [33]:
print("Elements in Z before")
z
z<-c(z,"annette")
print("Elements in Z after adding new elements")
z


[1] "Elements in Z before"


[1] "sarah" "tracy" "Vamsi"

[1] "Elements in Z after adding new elements"


[1] "sarah"   "tracy"   "Vamsi"   "annette"

In [34]:
print("Elements in Z before")
z
z<-c("Greg",z)
print("Elements in Z after adding new elements")
z


[1] "Elements in Z before"


[1] "sarah"   "tracy"   "Vamsi"   "annette"

[1] "Elements in Z after adding new elements"


[1] "Greg"    "sarah"   "tracy"   "Vamsi"   "annette"

In [35]:
a<-1:10
a

[1]  1  2  3  4  5  6  7  8  9 10

In [36]:
seq(10)

[1]  1  2  3  4  5  6  7  8  9 10

In [37]:
seq(from = 1,to=10,by=0.1)

[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

In [38]:
1/0


[1] Inf

In [39]:
0/0

[1] NaN

In [41]:
exp(Inf)

[1] Inf

In [42]:
exp(-Inf)

[1] 0

In [43]:
Inf-Inf

[1] NaN

In [44]:
log(0)

[1] -Inf

In [45]:
log(1)

[1] 0

In [46]:
a<-c(1.7,"a")
a

[1] "1.7" "a"

In [47]:
b<-c(TRUE,2,3,FALSE)
b

[1] 1 2 3 0

In [48]:
c<-c("a",TRUE)
c

[1] "a"    "TRUE"

In [49]:
as.numeric("1")

[1] 1

In [50]:
as.numeric(c("45","66"))

[1] 45 66

In [51]:
as.numeric(c("45","66","six"))

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] 45 66 NA

In [52]:
as.character(22)

[1] "22"

In [53]:
as.character(c(22,34,56))

[1] "22" "34" "56"

In [54]:
m<-matrix(nrow=2,ncol=2)
m

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

In [55]:
dim(m)

[1] 2 2

In [56]:
class(m)

[1] "matrix"

In [57]:
typeof(m)

[1] "logical"

In [58]:
m<-matrix(c(1:3))
print('Given matrix is:')
print(m)
print('dimensions (size) of given matrix is;')
print(dim(m))
print('class of given matix is:')
print(class(m))
print('type of given matrix is:')
print(typeof(m))

[1] "Given matrix is:"
     [,1]
[1,]    1
[2,]    2
[3,]    3
[1] "dimensions (size) of given matrix is;"
[1] 3 1
[1] "class of given matix is:"
[1] "matrix"
[1] "type of given matrix is:"
[1] "integer"


In [60]:
a<-matrix(1:6,nrow=2,ncol=3)
print(a)


     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [61]:
m<-1:10
print(m)
print(dim(m))
dim(m)<-c(2,5)
print(m)
print(dim(m))

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


In [62]:
my_name<- readline(prompt="Enter name:")
my_age<- readline(prompt="Enter age:")
my_age<- as.integer(my_age)
print(paste("Hi",my_name,"next year you will be",my_age+1,"years old"))


Enter name:Vamsi Krishna
Enter age:18
[1] "Hi Vamsi Krishna next year you will be 19 years old"


In [63]:
w<-readline()
w

Hello World!!!!!!!!!!!!!!!!


[1] "Hello World!!!!!!!!!!!!!!!!"

In [65]:
g=62.4
-g

[1] -62.4

In [66]:
s=as.integer(3.14)

In [67]:
s=as.integer(3)
s

[1] 3

In [68]:
k=1+2i
k

[1] 1+2i

In [69]:
sqrt(-1)

Warning message in sqrt(-1):
“NaNs produced”

[1] NaN

In [77]:
a = 4 ; b = 6
c = a > b
c

[1] FALSE

In [79]:
g=as.character(62.48)
g

[1] "62.48"

In [82]:
class(s)

[1] "integer"